CREATE TABLE "redirect_logs" (
	"created_at" timestamp with time zone DEFAULT now(),
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"redirected_url" text NOT NULL,
	"user_agent" text
);
--> statement-breakpoint
ALTER TABLE "current_segment" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "current_segment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);